version: '3.2'

services:

  stack-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inmana
    ports:
      - '15432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - stack
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "URMAIL@MAIL.com"
      PGADMIN_DEFAULT_PASSWORD: "PASSWORD"
    depends_on:
      - stack-postgres
    ports:
      - "5050:80"
    networks:
      - stack
    restart: unless-stopped

volumes:
  api:
  database_postgres:                 
  
networks:
  stack:
    driver: bridge
